modules/Page/Http/routes.php
<?php
Route::group(['middleware' => ['web', 'pages']], function () {
	
	Route::get('{slug}', [
		'as' 	=> 'pages.slug',
		'uses' 	=> 'Modules\Page\Http\Controllers\PageController@show'
	])->where('slug', Page::allSlug());
	
});
/*
 * Админка
 */


Route::group(['middleware' => ['web', 'admin'], 'prefix' => 'admin', 'namespace' => 'Modules\Page\Http\Controllers'], function()
{
	Route::resource('pages', 'PageController');
});

modules/Page/Entities/Page.php
<?php namespace Modules\Page\Entities;
   
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Page extends Model implements SluggableInterface {

    use SluggableTrait;
    
    protected $table = 'pages';

    protected $fillable = [];
    
    protected $guarded = ['_token', 'meta'];
    
    protected $sluggable = [
        'build_from' => 'name',
        'save_to'    => 'slug',
        'on_update'  => false,
    ];
    
    /* public function allSlug
     * @param $id
     *-----------------------------------
     *|
     *-----------------------------------
     */
    
    public static function allSlug() {
        
        $slugs = Page::all();
        
        $items = [];
        
        
        if($slugs->count())
        {
            foreach($slugs as $slug)
            {
                $items[] = $slug->slug;
            }
            
            $route = implode('|', $items);
            
        }
        else
        {
            $route = '[a-z]+';
        }
        
        return $route;
        
    }
    
    /* public function meta
     * @param $id
     *-----------------------------------
     *|
     *-----------------------------------
     */
    
    public function meta() {
        return $this->hasOne('Meta', 'entity_id', 'id')->where('entity', 'pages');
    }
    
    /* public function getStatussAttribute
     * @param $id
     *-----------------------------------
     *|
     *-----------------------------------
     */
    
    public function getStatussAttribute() {
        
        switch($this->status)
        {
            case 0:
                return 'Не опубликовано';
            break;
        
            case 1:
                return 'Опубликовано';
            break;
        }
        
    }
    
    /* public function getDateAttribute
     * @param $id
     *-----------------------------------
     *|
     *-----------------------------------
     */
    
    public function getDateAttribute() {
        return date('d.m.Y', strtotime($this->created_at));
    }
    

}

modules/Page/Http/Controllers/PageController.php
<?php namespace Modules\Page\Http\Controllers;

use Pingpong\Modules\Routing\Controller;

class PageController extends Controller {
	
	public function index()
	{
		$pages = \Page::orderBy('created_at', 'DESC')->paginate(20);
		
		return view('page::admin.index', compact('pages'));
	}
	
	/* public function create
	 * @param $id
	 *-----------------------------------
	 *|
	 *-----------------------------------
	 */
	
	public function create() {
		return view('page::admin.create');
	}
	
	public function store(\Modules\Page\Http\Requests\CreatePageReq $request)
	{
	    
	    $user = \Sentinel::getUser();
	    $data = $request->all();
	    $data['user_id'] = $user->id;
	    
	    $page = \Page::create($data);
	    
	    \Meta::set($page->id, $request->meta);
	    
	    return redirect()->route('pages.slug', $page->slug)->with('success', 'Страница создана.');
	}
	
	/**
	* Display the specified resource.
	*
	* @param  int  $id
	* @return Response
	*/
	public function show($slug)
	{
		$page = \Page::where('slug', $slug)->with('meta')->first();
		
		if (!$page || $page->status == 0) {
		    abort(404);
		}
		
		\MetaTag::set('title',  (empty($page->meta) || $page->meta->title == '') ? $page->name : $page->meta->title);
		\MetaTag::set('robots', !empty($page->meta) ? $page->meta->robots : '');
		\MetaTag::set('description', !empty($page->meta) ? $page->meta->description : '');
		\MetaTag::set('keywords', !empty($page->meta) ? $page->meta->keywords : '');
	   
		ob_start();
		print eval('?>' . $page->body);
		$body = ob_get_contents();
		ob_end_clean();
		
		return view('page::site.page-show', compact('page', 'body'));
        }
   
       /**
	* Show the form for editing the specified resource.
	*
	* @param  int  $id
	* @return Response
	*/
       public function edit($id)
       {
	   $page = \Page::findOrFail($id);
		
	   return view('page::admin.edit', compact('page'));
       }
   
       /**
	* Update the specified resource in storage.
	*
	* @param  int  $id
	* @return Response
	*/
       public function update(\Modules\Page\Http\Requests\CreatePageReq $request, $id)
       {       
	   $page = \Page::findOrFail($id);
	   $page->update($request->all());
	   \Meta::updateMeta($request->meta);
		
	   return redirect()->route('pages.slug', $page->slug)->with('success', 'Страница обновлена.');
       }
   
       /**
	* Remove the specified resource from storage.
	*
	* @param  int  $id
	* @return Response
	*/
       public function destroy($id)
       {
	   $page = \Page::findOrFail($id);
	   \Meta::deleteMeta('pages', $id);
	   $page->delete();
       
	   return redirect()->route('admin.pages.index')->with('success', 'Страница удалена.');
       }
	
}

modules/Page/Resources/views/admin/create.blade.php
@extends('admin::layouts.master')

@section('content')

<section class="content-header">
    <h1>{{ MetaTag::set('title', 'Создать страницу') }}</h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Главная</a></li>
        <li class="active">Создать страницу</li>
    </ol>
</section>
  
<section class="content">

    <div class="box">
        <div class="box-header with-border">
            
        </div>
        
        <div class="box-body">
            {!! Form::open(array('route' => 'admin.pages.store', 'role' => 'form', 'class' => 'form')) !!}
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name">Название *</label>
                    {!! Form::text('name', null, array('class' => 'form-control')) !!}
                </div>
                    
                <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                    <label for="body">Содержимое *</label>
                    {!! Form::textarea('body', null, array('class' => 'form-control wredaktor', 'rows' => 10)) !!}
                </div>
                    
                @include('meta::admin.form-meta', ['meta' => null, 'entity' => 'pages', 'entity_id' => null])
                    
                <div class="form-group">
                    {!! Form::hidden('status', 0) !!}
                    <label for="status" class="icheck">
                        {!! Form::checkbox('status', 1, 1) !!}
                        Опубликовать
                    </label>
                </div>
                    
                <div class="form-group">
                   {!! Form::submit('Сохранить', array('class' => 'btn btn-primary btn-flat')) !!}
                </div>
            {!! Form::close() !!}
        </div><!-- /.box-body -->
        
        <div class="box-footer">
         
        </div><!-- /.box-footer-->
    </div>

</section>

@stop

modules/Page/Resources/views/admin/edit.blade.php
@extends('admin::layouts.master')

@section('content')

<section class="content-header">
    <h1>{{ MetaTag::set('title', 'Редактировать страницу') }}</h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Главная</a></li>
        <li class="active">Редактировать страницу</li>
    </ol>
</section>
  
<section class="content">

    <div class="box">
        <div class="box-header with-border">
            
        </div>
        
        <div class="box-body">
            {!! Form::open(array('route' => ['admin.pages.update', $page->id], 'method' => 'PUT', 'role' => 'form', 'class' => 'form')) !!}
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name">Название *</label>
                    {!! Form::text('name', $page->name, array('class' => 'form-control')) !!}
                </div>
                    
                <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                    <label for="body">Содержимое *</label>
                    {!! Form::textarea('body', $page->body, array('class' => 'form-control wredaktor', 'rows' => 10)) !!}
                </div>
                    
                @include('meta::admin.form-meta', ['meta' => $page->meta, 'entity' => 'pages', 'entity_id' => $page->id])
                    
                <div class="form-group">
                    {!! Form::hidden('status', 0) !!}
                    <label for="status" class="icheck">
                        {!! Form::checkbox('status', 1, $page->status) !!}
                        Опубликовать
                    </label>
                </div>
                    
                <div class="form-group">
                   {!! Form::submit('Сохранить', array('class' => 'btn btn-primary btn-flat')) !!}
                </div>
            {!! Form::close() !!}
        </div><!-- /.box-body -->
        
        <div class="box-footer">
         
        </div><!-- /.box-footer-->
    </div>

</section>

@stop

modules/Page/Resources/views/admin/index.blade.php
@extends('admin::layouts.master')

@section('content')

<section class="content-header">
	<h1>{{ MetaTag::set('title', 'Страницы') }}</h1>
	<ol class="breadcrumb">
		<li><a href="/admin"><i class="fa fa-dashboard"></i> Главная</a></li>
		<li class="active">Страницы</li>
	</ol>
</section>
  
<section class="content">

	<div class="box">
		<div class="box-header with-border">
			@if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('pages.create'))
				<a class="btn btn-success btn-flat" href="{{ route('admin.pages.create') }}">Создать</a>
			@endif
		</div>
		
		<div class="box-body">
			@if($pages->count())
			<table class="table table-bordered b-c-222D32">
				<thead>
					<tr>
						<th width="10">#</th>
						<th>Название</th>
						<th width="150">Дата</th>
						<th width="150">Статус</th>
						<th width="100">Действие</th>
					</tr>
				</thead>
				<tbody>
					@foreach($pages as $item)
					<tr>
						<td>{{ $item->id }}</td>
						<td><a href="{{ route('pages.slug', $item->slug) }}">{{ $item->name }}</a></td>
						<td>{{ $item->date }}</td>
						<td>{{ $item->statuss }}</td>
						<td>
							@if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('pages.edit'))
								<a href="{{ route('admin.pages.edit', $item->id) }}" class="btn btn-sm bg-navy btn-flat"><i class="fa fa-fw fa-edit"></i></a>
							@endif
							
							@if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('pages.delete'))
								@include('cms::admin.delete', ['route' => 'admin.pages.destroy', 'id' => $item->id])
							@endif
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			{!! $pages->render() !!}
			@else
				<p>Нет страниц.</p>
			@endif
		  
		</div><!-- /.box-body -->
		
		<div class="box-footer">
		 
		</div><!-- /.box-footer-->
	</div>

</section>

@stop