modules/Taxonomy/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'prefix' => 'taxonomy', 'namespace' => 'Modules\Taxonomy\Http\Controllers'], function()
{
	Route::get('/', 'TaxonomyController@index');
});

/*
 * Админка
 */
Route::group(['middleware' => ['web', 'admin'], 'prefix' => 'admin', 'namespace' => 'Modules\Taxonomy\Http\Controllers'], function()
{
	Route::resource('taxonomy', 'TaxonomyController');
	Route::resource('taxonomy/term', 'TaxonomyTermController');
	Route::post('taxonomy/term/sort', 'TaxonomyTermController@sort');
});

modules/Taxonomy/Resources/views/admin/create.blade.php
@extends('admin::layouts.master')

@section('content')

<section class="content-header">
    <h1>{{ MetaTag::set('title', 'Создать словарь таксономии') }}</h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Главная</a></li>
        <li class="active">Создать словарь таксономии</li>
    </ol>
</section>
  
<section class="content">

    <div class="box">
        <div class="box-header with-border">
            
        </div>
        
        <div class="box-body">
            {!! Form::open(array('route' => 'admin.taxonomy.store', 'role' => 'form', 'class' => 'form')) !!}
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name">Название *</label>
                    {!! Form::text('name', null, array('class' => 'form-control')) !!}
                </div>
                    
                <div class="form-group">
                   {!! Form::submit('Сохранить', array('class' => 'btn btn-primary btn-flat')) !!}
                </div>
            {!! Form::close() !!}
        </div><!-- /.box-body -->
        
        <div class="box-footer">
         
        </div><!-- /.box-footer-->
    </div>

</section>

@stop

modules/Taxonomy/Resources/views/admin/edit.blade.php
@extends('admin::layouts.master')

@section('content')

<section class="content-header">
    <h1>{{ MetaTag::set('title', 'Редактировать словарь таксономии') }}</h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Главная</a></li>
        <li class="active">Редактировать словарь таксономии</li>
    </ol>
</section>
  
<section class="content">

    <div class="box">
        <div class="box-header with-border">
            
        </div>
        
        <div class="box-body">
            {!! Form::open(array('route' => ['admin.taxonomy.update', $taxonomy->id], 'method' => 'PUT', 'role' => 'form', 'class' => 'form')) !!}
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name">Название *</label>
                    {!! Form::text('name', $taxonomy->name, array('class' => 'form-control')) !!}
                </div>
                    
                <div class="form-group">
                   {!! Form::submit('Сохранить', array('class' => 'btn btn-primary btn-flat')) !!}
                </div>
            {!! Form::close() !!}
        </div><!-- /.box-body -->
        
        <div class="box-footer">
         
        </div><!-- /.box-footer-->
    </div>

</section>

@stop

modules/Taxonomy/Resources/views/admin/index.blade.php
@extends('admin::layouts.master')

@section('content')

<section class="content-header">
	<h1>{{ MetaTag::set('title', 'Словари таксономии') }}</h1>
	<ol class="breadcrumb">
		<li><a href="/admin"><i class="fa fa-dashboard"></i> Главная</a></li>
		<li class="active">Словари таксономи</li>
	</ol>
</section>
  
<section class="content">

	<div class="box">
		<div class="box-header with-border">
			@if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('taxonomy.create'))
				<a class="btn btn-success btn-flat" href="{{ route('admin.taxonomy.create') }}">Создать</a>
			@endif
		</div>
		
		<div class="box-body">
			@if($taxonomy->count())
			<table class="table table-bordered b-c-222D32">
				<thead>
					<tr>
						<th width="10">#</th>
						<th>Название меню</th>
						<th width="100">Действие</th>
					</tr>
				</thead>
				<tbody>
					@foreach($taxonomy as $item)
					<tr>
						<td>{{ $item->id }}</td>
						<td>
						@if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('taxonomy.create'))
							<a href="{{ route('admin.taxonomy.show', $item->id) }}">{{ $item->name }}</a>
						@else
							{{ $item->name }}
						@endif
						</td>
						<td>
							@if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('taxonomy.edit'))
								<a href="{{ route('admin.taxonomy.edit', $item->id) }}" class="btn btn-sm bg-navy btn-flat"><i class="fa fa-fw fa-edit"></i></a>
							@endif
							@if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('taxonomy.delete'))
								@include('cms::admin.delete', ['route' => 'admin.taxonomy.destroy', 'id' => $item->id])
							@endif
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			@else
				<p>Нет словарей.</p>
			@endif
		  
		</div><!-- /.box-body -->
		
		<div class="box-footer">
		 
		</div><!-- /.box-footer-->
	</div>

</section>

@stop

modules/Taxonomy/Resources/views/admin/show.blade.php
@extends('admin::layouts.master')

@section('content')

<section class="content-header">
    <h1>{{ MetaTag::set('title', $taxonomy->name) }}</h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Главная</a></li>
        <li class="active">{{ $taxonomy->name }}</li>
    </ol>
</section>
  
<section class="content">

    <div class="box">
        <div class="box-header with-border">
            <a href="{{ route('admin.taxonomy.term.create') }}?taxonomy_id={{ $taxonomy->id }}" class="btn btn-success btn-flat">Добавить термин</a>
            <a href="javascript:" data-action="collapseAll" class="btn btn-flat btn-s-md btn-danger m-r-20 anes"><i class="fa fa-arrow-circle-o-up"></i> Свернуть</a>
            <a href="javascript:" data-action="expandAll" class="btn btn-flat btn-s-md btn-warning anes"><i class="fa fa-arrow-circle-o-down"></i> Развернуть</a>
        </div>
        
        <div class="box-body">
            @if($taxonomy->terms->count())
                <div id="tree-admin" class="dd dd-term">
                    @include('taxonomy::admin.terms.lists', ['lists' => $taxonomy->terms->toHierarchy()])
                </div>
            @else
                <p>Нет терминов таксономии.</p>
            @endif
        </div><!-- /.box-body -->
        
        <div class="box-footer">
         
        </div><!-- /.box-footer-->
    </div>

</section>

@stop