modules/Advert/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'prefix' => 'adverts', 'namespace' => 'Modules\Advert\Http\Controllers'], function()
{
	Route::get('{category}', [
		'middleware' 	=> ['Modules\Advert\Http\Middleware\ViewMiddleware'],
		'as' 		=> 'adverts.category',
		'uses' 		=> 'AdvertController@category'
	])->where('category', TaxonomyTerm::allSlug());
	
	Route::get('add', [
		'middleware' 	=> ['Modules\Advert\Http\Middleware\CreateMiddleware'],
		'as' 		=> 'adverts.add',
		'uses' 		=> 'AdvertController@add'
	]);
	
	Route::get('add/{category}', [
		'middleware' 	=> ['Modules\Advert\Http\Middleware\CreateMiddleware'],
		'as' 		=> 'adverts.add.category',
		'uses' 		=> 'AdvertController@addCategory'
	]);
	
	Route::post('get/phone', [
		'as' 	=> 'adverts.get.phone',
		'uses' 	=> 'AdvertController@getPhone'
	]);
	
	Route::get('sendmessage', [
		'as' 	=> 'adverts.sendmessage',
		'uses' 	=> 'AdvertController@sendmessage'
	]);
	
	Route::post('sendmessage', [
		'as' 	=> 'adverts.sendmessage',
		'uses' 	=> 'AdvertController@sendmessagePost'
	]);
	
	Route::get('complain', [
		'as' 	=> 'adverts.complain',
		'uses' 	=> 'AdvertController@complain'
	]);
	
	Route::post('complain', [
		'as' 	=> 'adverts.complain',
		'uses' 	=> 'AdvertController@complainPost'
	]);
	
	Route::get('load/{category}', [
		'as' 	=> 'adverts.load.category',
		'uses' 	=> 'AdvertController@loadCategory'
	]);
	
	Route::post('check/mail', [
		'as' 	=> 'adverts.check.mail',
		'uses' 	=> 'AdvertController@checkMail'
	]);
	
	
});

Route::group(['middleware' => 'web', 'namespace' => 'Modules\Advert\Http\Controllers'], function()
{
	Route::resource('nedvizhimost', 'NedvizhimostController');
	Route::resource('transport', 'TransportController');
	Route::resource('rabota-i-obrazovanie', 'RabotaController');
	Route::resource('uslugi-i-deyatelnost', 'UslugiController');
	Route::resource('biznes-i-partnerstvo', 'BiznesController');
	Route::resource('elektronika', 'ElektronikaController');
	Route::resource('dom-i-sad', 'DomsadController');
	Route::resource('zhivotnye-i-rasteniya', 'ZhivotnyeController');
	Route::resource('odezhda-i-aksesuary', 'OdezhdaController');
	Route::resource('krasota-i-zdorove', 'KrasotaController');
	Route::resource('detskiy-mir', 'DetskiyController');
	Route::resource('sport-otdykh-khobbi', 'SportController');
	Route::resource('otdam-darom', 'OtdamController');
	Route::resource('obmen-i-barakholka', 'ObmenController');
	Route::resource('drugoe', 'DrugoeController');
	
	
	Route::get('user/{id}/adverts', [
		'middleware' 	=> 'auth',
		'as' 		=> 'user.adverts',
		'uses' 		=> 'AdvertController@userAdverts'
	]);
	
	Route::post('search', [
		'as' 	=> 'adverts.search',
		'uses' 	=> 'AdvertController@search'
	]);
	
	Route::post('favorites/add', [
		'as' 	=> 'adverts.favorites.add',
		'uses' 	=> 'AdvertController@favoritesAdd'
	]);
	
	Route::get('favorites', [
		'as' 	=> 'adverts.favorites',
		'uses' 	=> 'AdvertController@favorites'
	]);
	
	Route::post('favorites/del', [
		'as' 	=> 'adverts.favorites.del',
		'uses' 	=> 'AdvertController@favoritesDel'
	]);
	
	Route::post('advert/{id}/public', [
		'as' 	=> 'advert.id.public',
		'uses' 	=> 'AdvertController@advertPublic'
	]);
	
	Route::post('advert/{id}/unpublic', [
		'as' 	=> 'advert.id.unpublic',
		'uses' 	=> 'AdvertController@advertUnPublic'
	]);
	
	Route::delete('advert/{id}/delete', [
		'as' 	=> 'advert.id.delete',
		'uses' 	=> 'AdvertController@advertDelete'
	]);
});

/*
 * Админка
 */
Route::group(['middleware' => ['web', 'admin'], 'prefix' => 'admin', 'namespace' => 'Modules\Advert\Http\Controllers'], function()
{
	Route::resource('adverts', 'AdminAdvertController');
    
	Route::post('advert/{id}/public', [
		'as' 	=> 'admin.advert.id.public',
		'uses' 	=> 'AdminAdvertController@advertPublic'
	]);
	    
	Route::post('advert/{id}/unpublic', [
		'as' 	=> 'admin.advert.id.unpublic',
		'uses' 	=> 'AdminAdvertController@advertUnPublic'
	]);
	
	Route::post('advert/{id}/cancel', [
		'as' 	=> 'admin.advert.id.cancel',
		'uses' 	=> 'AdminAdvertController@advertCancel'
	]);
	
	Route::get('adverts/status/{status}', [
		'as' 	=> 'admin.adverts.status',
		'uses' 	=> 'AdminAdvertController@advertStatus'
	]);
	
	Route::delete('advert/{id}/deladmin', [
		'as' 	=> 'admin.advert.id.deladmin',
		'uses' 	=> 'AdminAdvertController@deladmin'
	]);
    
});

modules/Advert/Resources/views/admin/filter.blade.php
<div id="admin-advert-filter">
    {!! Form::open(array('url' => Request::url(), 'role' => 'form', 'class' => 'form', 'method' => 'GET')) !!}
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="type">Тип объявления</label>
                    {!! Form::select('type', $types, Request::get('type'), array('class' => 'form-control selectpicker', 'title' => '- Выбрать -')) !!}
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="name">Название</label>
                    {!! Form::text('name', Request::get('name'), array('class' => 'form-control')) !!}
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">
                    <label for="avtor">Автор</label>
                    {!! Form::text('avtor', Request::get('avtor'), array('class' => 'form-control')) !!}
                </div>
            </div>
            <div class="col-lg-3" style="padding-top:25px;">
                {!! Form::submit('Применить', array('class' => 'btn btn-primary')) !!}
                <a class="btn btn-info" href="{{ Request::url() }}">Сбросить</a>
            </div>
        </div>
    {!! Form::close() !!}
</div>

modules/Advert/Resources/views/admin/index.blade.php
@extends('admin::layouts.master')

@section('content')

<section class="content-header">
    <h1>{{ MetaTag::set('title', 'Объявления') }}</h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i> Главная</a></li>
        <li class="active">Объявления</li>
    </ol>
</section>
  
<section class="content">

    <div class="box">
        <div class="box-header with-border">
            @if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('advert.create'))
            <div class="btn-group m-b-20">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Добавить <span class="caret"></span></button>
                <ul class="dropdown-menu" role="menu">
                    @foreach($categories as $category)
                        <li><a href="{{ route('adverts.add.category', $category->slug) }}">{{ $category->name }}</a></li>
                    @endforeach
                </ul>
            </div>
            @endif
            @include('advert::admin.tabs')
            @include('advert::admin.filter', ['types' => $types])
        </div>
        
        <div class="box-body">
            @if($adverts->count())
            <table class="table table-bordered b-c-222D32">
                <thead>
                    <tr>
                        <th width="10">#</th>
                        <th width="150">Тип</th>
                        <th>Название</th>
                        <th width="200">Автор</th>
                        <th>Опубликовано</th>
                        <th width="150">Статус</th>
                        <th width="150">Действие</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($adverts as $item)
                    <tr>
                        <td>{{ $item->id }}</td>
                        <td>{{ $item->type }}</td>
                        <td><a href="{{ route($item->type.'.show', $item->id) }}">{{ $item->name }}</a></td>
                        <td><a href="{{ route('user.slug', $item->user->slug) }}">{{ $item->user->name }}</a></td>
                        <td>{{ $item->date }}</td>
                        <td>{{ $item->statuss }}</td>
                        <td>
                            @if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('advert.edit'))
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Редактировать <span class="caret"></span></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a class="ajax ajax-form" data-method="POST" href="{{ route('admin.advert.id.public', $item->id) }}"><i class="fa fa-check-square-o" aria-hidden="true"></i> Опубликовать</a>
                                    </li>
                                    <li>
                                        <a href="{{ route($item->type.'.edit', $item->id) }}"><i class="fa fa-fw fa-edit"></i> Изменить</a>
                                    </li>
                                     @if(Sentinel::getUser()->inRole('admin') || Sentinel::getUser()->hasAccess('advert.delete'))
                                    <li>
                                        <a class="delete" data-method="DELETE" data-button2="Нет" data-button1="Да" data-message="Это действие необратимо!" data-title="Хотите удалить?" data-href="{{ route('admin.adverts.destroy', $item->id) }}" href="javascript:">
                                            <i class="fa fa-fw fa-trash-o"></i> Удалить
                                        </a>
                                    </li>
                                    <li>
                                        <a class="delete" data-method="DELETE" data-button2="Нет" data-button1="Да" data-message="Это действие необратимо!" data-title="Хотите удалить?" data-href="{{ route('admin.advert.id.deladmin', $item->id) }}" href="javascript:">
                                            <i class="fa fa-fw fa-trash-o"></i> Удалить из админки
                                        </a>
                                    </li>
                                    @endif
                                    <li>
                                        <a class="ajax ajax-form" data-method="POST" href="{{ route('admin.advert.id.unpublic', $item->id) }}"><i class="fa fa-square-o" aria-hidden="true"></i> Снять с публикации</a>
                                    </li>
                                    <li>
                                        <a class="ajax ajax-form" data-method="POST" href="{{ route('admin.advert.id.cancel', $item->id) }}"><i class="fa fa-times" aria-hidden="true"></i> Отклонить</a>
                                    </li>
                                </ul>
                            </div>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $adverts->render() !!}
            @else
                <p>Нет объявлений.</p>
            @endif
        </div><!-- /.box-body -->
        
        <div class="box-footer">
         
        </div><!-- /.box-footer-->
    </div>

</section>
@stop

modules/Advert/Resources/views/admin/tabs.blade.php
<ul class="nav nav-tabs m-b-20">
    <li class="{{ active_class(if_uri(['admin/adverts/status/2', 'admin/adverts']), 'active') }}"><a href="{{ route('admin.adverts.status', 2) }}">На модерации <span class="badge">{{ Advert::countStatus(2) }}</span></a></li>
    <li class="{{ active_class(if_uri(['admin/adverts/status/3']), 'active') }}"><a href="{{ route('admin.adverts.status', 3) }}">Отклоненые модератором <span class="badge">{{ Advert::countStatus(3) }}</span></a></li>
    <li class="{{ active_class(if_uri(['admin/adverts/status/1']), 'active') }}"><a href="{{ route('admin.adverts.status', 1) }}">Опубликованые <span class="badge">{{ Advert::countStatus(1) }}</span></a></li>
    <li class="{{ active_class(if_uri(['admin/adverts/status/0']), 'active') }}"><a href="{{ route('admin.adverts.status', 0) }}">Снятые с публикации <span class="badge">{{ Advert::countStatus(0) }}</span></a></li>
</ul>